title: "Jon Schwenk"
description: "Hydro- and river-ologist | Software Developer | Data Scientist | Solving Practical Problems | ...and fun ones"
theme: minima

# Useful links for the header/footer
author:
  name: "Jon Schwenk"
  email: "jonschwenk@gmail.com"

# Disable blog posts for now (we'll just use pages/sections)
show_excerpts: false
